[package]
name = "openocr"
version = "0.1.0"
edition = "2024"

[features]
devtools = ["freya/devtools"]

[dependencies]
winit = "0.29"
softbuffer = "0.4"
xcap = "0.0.14"
image = "0.25.9"
base64 = "0.22.1"
ollama-rs = "0.3.4"
tokio = { version = "1.50.0", features = ["full"] }
rig-core = "0.31.0"
reqwest = { version = "0.12", default-features = false, features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
freya = { git = "https://github.com/marc2332/freya.git", rev = "refs/pull/1655/head", features = [
  "icons",
  "devtools",
] }
clap = { version = "4.6.0", features = ["derive"] }
tw-colors = "0.1.0"
